# Generated by Django 4.2.29 on 2026-04-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('LIBRARY_SEAT', 'Library Seat'), ('STUDENT_ROOM', 'Student Room'), ('STUDY_ROOM', 'Study Room'), ('COMPUTER_LAB', 'Computer Lab'), ('DISCUSSION_ROOM', 'Discussion Room'), ('SEMINAR_HALL', 'Seminar Hall'), ('MUSIC_ROOM', 'Music Room'), ('PRINTING_LAB', 'Printing Lab')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('building', models.CharField(max_length=150)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number', models.CharField(blank=True, max_length=30, null=True)),
                ('total_capacity', models.PositiveSmallIntegerField()),
                ('requires_approval', models.BooleanField(default=False)),
                ('min_group_size', models.PositiveSmallIntegerField(default=1)),
                ('max_booking_duration_mins', models.PositiveSmallIntegerField(default=120)),
                ('slot_duration_mins', models.PositiveSmallIntegerField(default=60)),
                ('images', models.JSONField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_capacity', models.PositiveSmallIntegerField()),
                ('booked_count', models.PositiveSmallIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='facilities.facility')),
            ],
            options={
                'unique_together': {('facility', 'slot_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=100)),
                ('rule_value', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='facilities.facility')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('facility', 'rule_key')},
            },
        ),
    ]
