# Generated by Django 4.2.29 on 2026-04-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cleanliness_rating', models.PositiveSmallIntegerField()),
                ('equipment_rating', models.PositiveSmallIntegerField()),
                ('experience_rating', models.PositiveSmallIntegerField()),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='feedback', to='bookings.booking')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedbacks', to='facilities.facility')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, max_length=36, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_bookings', models.PositiveSmallIntegerField(default=0)),
                ('confirmed_bookings', models.PositiveSmallIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveSmallIntegerField(default=0)),
                ('no_show_count', models.PositiveSmallIntegerField(default=0)),
                ('utilization_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('peak_hour_start', models.TimeField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('unique_students', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='facilities.facility')),
            ],
            options={
                'unique_together': {('facility', 'snapshot_date')},
            },
        ),
    ]
