# Generated by Django 6.0.3 on 2026-04-03 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('library', 'Library Seat'), ('study_room', 'Study Room'), ('computer_lab', 'Computer Lab'), ('discussion', 'Discussion Room'), ('seminar', 'Seminar Hall'), ('music', 'Music Practice Room'), ('3d_print', '3D Printing Lab')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('capacity_per_slot', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='facilities.facility')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('facility', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
