# Generated by Django 4.2.29 on 2026-04-02 16:50

import apps.bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('booking_reference', models.CharField(default=apps.bookings.models.generate_booking_reference, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('seat_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group_size', models.PositiveSmallIntegerField(default=1)),
                ('group_members', models.JSONField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=300, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='facilities.facility')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='facilities.facilityslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PROMOTED', 'Promoted'), ('EXPIRED', 'Expired'), ('REMOVED', 'Removed')], default='WAITING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='facilities.facilityslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'slot')},
            },
        ),
    ]
